[package]
name = "bangbang"
version = "0.1.0"
authors = ["Paul  d'Hubert <paul@tymate.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_codegen = "0.4.0"

nom = "*"

serde = "1.0.85"
serde_derive = "1.0.85"

percent-encoding = "1.0.1"
